<?xml version="1.0" encoding="UTF-8"?>
<test_result>
  <test_runs>
        <test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246800" external_run_id="A1"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246800" external_run_id="A2"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246800" external_run_id="A3"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246800" external_run_id="A4"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppA" duration="0" status="Passed" started="1602748246800" external_run_id="A5"/>
	  
        <test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B1"/>
        <test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B2"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B3"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B4"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B5"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Passed" started="1602748246800" external_run_id="B6"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppB" duration="0" status="Failed" started="1602748246800" external_run_id="B7">
	        <error type="java.lang.AssertionError" message="expected:'111' but was:'222'">java.lang.AssertionError: expected:'111' but was:'222'
			at org.junit.Assert.fail(Assert.java:88)
			at org.junit.Assert.failNotEquals(Assert.java:743)
			at org.junit.Assert.assertEquals(Assert.java:118)
	       </error>
	</test_run>
	  
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppC" duration="1" status="Passed" started="1602748246800" external_run_id="C1"/>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppC" duration="2" status="Failed" started="1602748246800" external_run_id="C2"/>
	  <error type="java.lang.AssertionError" message="expected:'111' but was:'222'">java.lang.AssertionError: expected:'111' but was:'222'
			at org.junit.Assert.fail(Assert.java:88)
			at org.junit.Assert.failNotEquals(Assert.java:743)
			at org.junit.Assert.assertEquals(Assert.java:118)
	       </error>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppC" duration="3" status="Skipped" started="1602748246800" external_run_id="C3"/>
	
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppD" duration="0" status="Failed" started="1602748246800" external_run_id="D4"/>
	  <error type="java.lang.AssertionError" message="expected:'111' but was:'222'">java.lang.AssertionError: expected:'111' but was:'222'
			at org.junit.Assert.fail(Assert.java:88)
			at org.junit.Assert.failNotEquals(Assert.java:743)
			at org.junit.Assert.assertEquals(Assert.java:118)
	       </error>
	<test_run module="" package="MF.simple.tests" class="AppTest" name="testAppD" duration="0" status="Skipped" started="1602748246800" external_run_id="D5"/>

  </test_runs>
</test_result>
